BUILD-909 updated release workflow for sonar-scanner-api
SonarSource/sonar-scanner-api pull request #104
Opened 2021-04-21 10:33 UTC by tobias-trabelsi-sonarsource

2021-04-21 11:36 UTC, malena-ebert-sonarsource requested changes

2021-04-21 11:36 UTC, malena-ebert-sonarsource commented on .github/workflows/release.yml
>            distribute: true
can be removed. not relevant anymore

2021-04-21 11:36 UTC, malena-ebert-sonarsource commented on pom.xml
> +    <version>57.0.19</version>
58.0.22

2021-04-21 11:58 UTC, tobias-trabelsi-sonarsource commented on .github/workflows/release.yml
>            distribute: true
the release action can be removed? Oô

2021-04-23 09:50 UTC, malena-ebert-sonarsource approved these changes

2021-04-23 09:51 UTC, merged